volumes:
        jun-pg-volume:
            external: true
            name: jun-pg-volume

services:
    db:
        image: postgres:16.2
        container_name: jun-pg
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - TZ=Asia/Seoul
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
        volumes:
            - jun-pg-volume:/var/lib/postgresql/data
