server:
    port: 8080
    address: 0.0.0.0

spring:
    config.import: classpath:password.yaml
    application.name: blog-du-cinema-back

    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/blog_du_cinema
        driver-class-name: org.postgresql.Driver
        username: root
    jpa:
        properties:
            hibernate.cache.hibernate.cache:
                use_query_cache: true
                use_second_level_cache: true


spring.jpa.hibernate.ddl-auto: validate

server.servlet.encoding:
    charset: utf-8
    enabled: true
    force: true

logging.level:
    root: DEBUG
    org.springframework.security: DEBUG